### ISSUE TITLE
How to start video streaming automatically when CameraDemoActivit is ready?

### ISSUE THREAD

**Issue by gushangzao007** [pedroSG94/RTSP-Server#102]
**My Target:**  start video streaming automatically when CameraDemoActivit is ready.

**What I have done:**  move following code to the onCreate function of CameraDemoActivit.

https://github.com/pedroSG94/RTSP-Server/blob/c72bf5a3563c220d9b14dba4b28d83fbe81d0fb5/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt#L99C21-L99C21

**What is the test result?**

1. video surface is always black in screen
2. got Error from Toast: connection faild , sps....is nulll..bla bla

could you help to advise a correct method to start streaming automatically?
Thank you very much。

**Comment by pedroSG94** [comment]
Hello,

You have that error because you need wait until the view is totally created. 
The view is created when this callback is called:
https://github.com/pedroSG94/RTSP-Server/blob/c72bf5a3563c220d9b14dba4b28d83fbe81d0fb5/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt#L169

That is the reason because I call start preview here and not in onCreate.
And destroyed in this one:
https://github.com/pedroSG94/RTSP-Server/blob/c72bf5a3563c220d9b14dba4b28d83fbe81d0fb5/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt#L173

**Comment by gushangzao007** [comment]
cool! work perfect! Thanks again!
