### ISSUE TITLE
How to Crop video frame using CropYuv....? Please help...!

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#12]
Hi Pedro,
I'm stuck in cropping the videoFrame.
I'm using camera2Base and two SurfaceView but dont know how to crop video using video encoder using CropYuv method from YUVUtil.java...
Please help....!!!

**Comment by pedroSG94** [comment]
You can't crop YUV with camera 2 because you haven't a YUV frame to crop.
This method is only for camera1 with SurfaceView or TextureView because you get that YUV frame here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L264.
I recommend you use OpenGlView and crop with glViewport as I told you in this post:
https://github.com/pedroSG94/RTSP-Server/issues/10
SurfaceView is really limited to customize.

**Comment by ankitda30** [comment]
> You can't crop YUV with camera 2 because you haven't a YUV frame to crop.
> This method is only for camera1 with SurfaceView or TextureView because you get that YUV frame here:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L264.
> I recommend you use OpenGlView and crop with glViewport as I told you in this post:
> #10
> SurfaceView is really limited to customize.

Ok But could you please tell me how to use multiple OpenGlView...?

**Comment by ankitda30** [comment]
I wanted to use two OpenGlView side by side...
What should I need to do....?
