### ISSUE TITLE
Is it support resolution 600 * 1024 and portrait screen.

### ISSUE THREAD

**Issue by Shaooooo** [pedroSG94/RTSP-Server#137]
Now my company changed new android device and screen. The rtsp server can't running normal. Can you guide me support new resolution ?

**Comment by pedroSG94** [comment]
Hello,

Can you explain more about your case?
Can you describe the error? share an image if necessary

**Comment by Shaooooo** [comment]
> Hello,
> 
> Can you explain more about your case? Can you describe the error? share an image if necessary

Thx your reply, I got the reason is follow method.

    if (!checkCanOpen()) {
      throw new CameraOpenException("This camera resolution cant be opened");
    }

Then I try to download the source code of RootEncoder library to the project RTSP-Server， I got a error of follow.

![image](https://github.com/user-attachments/assets/2c932bc9-de58-475c-a5a4-756c49da5274)

the latest version of RootEncoder library seems not updated to the RTSP-Server remote implementations. Could you give me some guide? maybe revert the version of RootEncoder . Or update the new version to RTSP-Server. Then I can run it and debug.

**Comment by pedroSG94** [comment]
Hello,

It is not related with the library version. As you can see the problem is related with the resolution that you are trying to open because that resolution is not supported by your camera. 
You should use a resolution supported by your camera or try migrate to RtspServerCamera2 that is more flexible in resolutions supported
