### ISSUE TITLE
How to use auth?

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/RTSP-Server#37]
I notice this isn't implemented 

override fun setAuthorization(user: String, password: String) { //not developed
  }

How would you recommend do this? thanks

**Comment by pedroSG94** [comment]
Hello,

This is not developed because I can't find a rtsp player with support for auth.
If you can find a player that support digest auth and basic auth I can add it to project.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/commands/CommandsManager.kt#L150
That auth should be send by player in rtsp methods:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/commands/CommandsManager.kt#L127

**Comment by ToysoftInc** [comment]
I found this link that talks about using vlc player

https://www.arcdyn.com/articles/use-rtsp-to-view-your-arcdyn-security-cameras-in-vlc-media-player/

I have the latest vlc player and using it to test your demo app.

Thanks

**Comment by ToysoftInc** [comment]
Here is a Youtube for vlc connecting to an ipcamera with user/password

https://www.youtube.com/watch?v=pZDP_Kf3oLk&ab_channel=Finchtech

**Comment by pedroSG94** [comment]
Ok, marked as feature. 

Thanks for the info

**Comment by ToysoftInc** [comment]
Thank you. Hope you add this feature soon.

**Comment by pedroSG94** [comment]
Rtsp basic auth is working now:
https://github.com/pedroSG94/RTSP-Server/commit/7d705ab3596056edba891253864e63fbe86dd767
I tested it using VLC. I have plan to develop digest auth too.

**Comment by ToysoftInc** [comment]
cool thx
what is the url format that you use with the auth in vlc? is it rtsp://user:password@ip:port ?
