### ISSUE TITLE
Can't set server address

### ISSUE THREAD

**Issue by Y2Kot** [pedroSG94/RTSP-Server#68]
Hello, Is it possible to set server address manually? I checked for now and find that methods unused. Am i right?

**Comment by pedroSG94** [comment]
What do you means with set address? The address is the device ip and port used in constructor.

Do you means application and stream name? Why do you need it if you haven't support for push?

**Comment by MalteHillmann** [comment]
I think the problem is, that in RtspServer.kt the IP-Address is automatically set by the private function getIPAddress:
https://github.com/pedroSG94/RTSP-Server/blob/a88620ec6e602d7ab8e933ee41593a78d2bce839/rtspserver/src/main/java/com/pedro/rtspserver/RtspServer.kt#L27

But when you are connected to a VPN the IP-Address responded by this function is wrong. Its the local cellular radio or wifi ip address instead of the VPN address. 
So yes, a function to override that server address or (in my case) the recognition of vpn addresses would be nice.

Kind regards
Malte

**Comment by Y2Kot** [comment]
adding pr #71 to solve this problem
