### ISSUE TITLE
How to add video channels 

### ISSUE THREAD

**Issue by mengmeng66** [pedroSG94/RTSP-Server#77]
How to add video channels such as (rtsp :// ip:port/channel)

**Comment by pedroSG94** [comment]
Hello,

Currently it isn't necessary because you haven't multiple stream sources. Stream push is not supported, only pull from a player is supported and the stream source depend of class used:
Camera1, Camera2, Display, FromFile, OnlyAudio
You can add any channel but the library ignore it because you don't need it.
