### ISSUE TITLE
OpenH264 check in library

### ISSUE THREAD

**Issue by prtbhtt** [pedroSG94/RTSP-Server#78]
I want to use H.264 encoder in your project.

Can you tell me if your project support OpenH264? 
I don't have much knowledge about video streaming. Can you tell me the definition of OpenH264 and the way it works?

Best Regards!

**Comment by pedroSG94** [comment]
Hello,

This project support H264 and H265 video encoders using MediaCodec class of Android. 
Since this project depend of:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java
You have the implementation here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/BaseEncoder.java
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/encoder/src/main/java/com/pedro/encoder/video
