### ISSUE TITLE
Stream URL change

### ISSUE THREAD

**Issue by ardarsln** [pedroSG94/RTSP-Server#84]
How do we change stream URL? I want to add stream name like: rtsp://ip:port/**streamName**.
There is a startStreamRtp(url) function call but it never implemented.

When I follow the function calls it goes like this:
- CameraDemoActivity: rtspServerCamera1.startStream()
- RtspServerCamera1: super.startStream("")
- Camera1Base: startStreamRtp(url): protected abstract void startStreamRtp(String url);

**Comment by ardarsln** [comment]
1) https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/b4ca9bd7569855dd0e9c261fc83c41fb7a10a951/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java#L152

In this example, it uses RtspClient and CommandsManager.

2) 
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServerCamera1.kt

But in this example, it uses RtspServer and ServerCommandManager.

I am a little bit confused which one we should use.

**Comment by pedroSG94** [comment]
Hello,

Depend of your requirements
The first one is used to push stream to a media server. 
The second one is used to pull data from a device to a player directly without a media server (it is the reason because you don't need a URL. The url is basically your IP that you can get from this:
https://github.com/pedroSG94/RTSP-Server/blob/master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt#L93
